name: Pre Release

on:
  push:
    branches:
      - main

jobs:
  windows-release-build:
    runs-on: windows-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Test
        run: python TONSign_Classic_or_Special_yky.py

      # Build python script into a stand-alone exe
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: TONSign_Classic_or_Special_yky.py
          standalone: true

      - name: Copy Language Folder
        run: Copy-Item -Path "Language" -Destination "build/TONSign_Classic_or_Special_yky.dist" -Recurse

      - name: Copy Link Files
        run: Copy-Item -Path "*.Ink" -Destination "build/TONSign_Classic_or_Special_yky.dist"

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'TONSign-Classic-or-Special-yky.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          directory: build/TONSign_Classic_or_Special_yky.dist

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: build/TONSign_Classic_or_Special_yky.dist/TONSign-Classic-or-Special-yky.zip

  asset-release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Repository
        uses: actions/checkout@v4

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'TONSignAsset.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.idea* *.github* *.vscode* /*Exe/* /*Language/* /*Screenshot/* .gitignore LICENSE *.md *.txt *.code-workspace *.py'

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset
          path: TONSignAsset.zip
  
  deploy:
    needs: [ windows-release-build, asset-release-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      - name: Generate Pre Release Tag
        id: release_tag
        run: |
          today=pre-v$(date +'%Y.%m.%d.%H%M%S')
          echo "release_tag=$today" >> $GITHUB_OUTPUT

      - name: Create Pre Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.release_tag.outputs.release_tag }}
          tag_name: ${{ steps.release_tag.outputs.release_tag }}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: true
          make_latest: true
          prerelease: true
          files: |
            release-windows/TONSign-Classic-or-Special-yky.zip
            release-asset/TONSignAsset.zip